package com.idemia.dob.utilclasses;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.SerializationFeature;
import com.fasterxml.jackson.datatype.jsr310.JavaTimeModule;

//@JsonInclude(JsonInclude.Include.NON_NULL)
public class ResponseHeader {
                             
	public ResponseHeader() {

	}

	/**
	 * Unique request identifier - echo value from the request
	 */
	private String requestId;

	/**
	 * Unique response identifier - generated by responding system
	 */
	private String responseId;

	/**
	 * Represents application level errors per Error code section of this document
	 */
	private int statusCode;

	/**
	 * Optional error message the provider can return
	 */
	private String statusMessage;

	/*    *//**
			 * Optional detailed error code specific to the provider
			 *//*
				 * private String subStatusCode;
				 */

	/**
	 * @param requestId
	 * @param responseId
	 * @param statusCode
	 * @param statusMessage
	 */
	public ResponseHeader(String requestId, String responseId, int statusCode, String statusMessage) {
		super();
		this.requestId = requestId;
		this.responseId = responseId;
		this.statusCode = statusCode;
		this.statusMessage = statusMessage;
	}

	public String getRequestId() {
		return requestId;
	}

	public String getResponseId() {
		return responseId;
	}

	public String getStatusMessage() {
		return statusMessage;
	}

	public void setRequestId(String requestId) {
		this.requestId = requestId;
	}

	public void setResponseId(String responseId) {
		this.responseId = responseId;
	}

	/*
	 * public String getSubStatusCode() { return subStatusCode; }
	 * 
	 * public void setSubStatusCode(String subStatusCode) { this.subStatusCode =
	 * subStatusCode; }
	 */

	public void setStatusMessage(String statusMessage) {
		this.statusMessage = statusMessage;
	}

	/**
	 * @return the statusCode
	 */
	public int getStatusCode() {
		return statusCode;
	}

	/**
	 * @param statusCode the statusCode to set
	 */
	public void setStatusCode(int statusCode) {
		this.statusCode = statusCode;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "ResponseHeader [requestId=" + requestId + ", responseId=" + responseId + ", statusCode=" + statusCode
				+ ", statusMessage=" + statusMessage + "]";
	}

	public String convertToJson() throws JsonProcessingException {
		if (this == null) {
			return null;
		}
		ObjectMapper mapper = new ObjectMapper();
		mapper.registerModule(new JavaTimeModule());
		mapper.disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS);

		return mapper.writeValueAsString(this);
	}
}
